"""Generate markdown/HTML reports for CI and documentation."""

from __future__ import annotations


from .schema import MCPServerSpec
from .analyzer import AnalysisReport, Severity


def generate_markdown(spec: MCPServerSpec, report: AnalysisReport) -> str:
    """Generate a markdown report suitable for PR comments."""
    lines = []

    # Header with badge
    grade = _grade(report.score)
    emoji = "✅" if report.passed else "❌"
    lines.append(f"## {emoji} mcpeval: {report.score}/100 ({grade})")
    lines.append("")
    lines.append(f"**{len(spec.tools)} tools** | **~{spec.total_tokens} tokens** | **{report.error_count} errors** | **{report.warning_count} warnings**")
    lines.append("")

    if report.issues:
        lines.append("### Issues")
        lines.append("")
        lines.append("| Severity | Tool | Issue | Suggestion |")
        lines.append("|----------|------|-------|------------|")

        for issue in sorted(report.issues, key=lambda i: (i.severity != Severity.ERROR, i.severity != Severity.WARNING)):
            sev = "🔴" if issue.severity == Severity.ERROR else "🟡" if issue.severity == Severity.WARNING else "⚪"
            lines.append(f"| {sev} | `{issue.tool}` | {issue.message} | {issue.suggestion} |")

        lines.append("")

    # Token breakdown
    lines.append("### Token Budget")
    lines.append("")
    lines.append("| Tool | Tokens | % |")
    lines.append("|------|--------|---|")
    for tool in sorted(spec.tools, key=lambda t: t.token_estimate, reverse=True):
        pct = tool.token_estimate / max(spec.total_tokens, 1) * 100
        lines.append(f"| `{tool.name}` | {tool.token_estimate} | {pct:.0f}% |")
    lines.append(f"| **Total** | **{spec.total_tokens}** | 100% |")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by [mcpeval](https://github.com/jashshah999/mcpeval)*")

    return "\n".join(lines)


def generate_badge_url(score: int) -> str:
    """Generate a shields.io badge URL for the score."""
    grade = _grade(score)
    color = "brightgreen" if score >= 80 else "yellow" if score >= 60 else "red"
    return f"https://img.shields.io/badge/mcpeval-{score}%2F100%20({grade})-{color}"


def _grade(score: int) -> str:
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 40:
        return "D"
    return "F"
